<?php
	return array(
        'default_title' => 'Larapay | Invoicing & Accounting',
    	'system_default' => [
            'theme_color' => 'default',
            'theme_font' => 'Open+Sans',
            'application_name' => 'Larapay | Invoicing & Accounting',
            'setup_guide' => 1,
            'timezone_id' => '266',
            'default_language' => 'en',
            'direction' => 'ltr',
            'error_display' => 1,
            'textarea_limit' => '300',
            'enable_password_strength_meter' => 1,
            'notification_position' => 'toast-bottom-right',
            'multilingual' => 1,
            'throttle_attempt' => 5,
            'throttle_lockout_period' => 2,
            'login_type' => null,
            'lock_screen_timeout' => 1,
            'cache_lifetime' => '100',
            'credit' => 'Designed with love by WM Lab',
            'celebration_days' => 30,
            'under_maintenance_message' => 'The system is under maitnenance.',
            'chat_refresh_duration' => 60,
            'hidden_value' => 'xxxxxxxxxxxxxxxx',
            'default_invoice_partial_payment' => '1',
            'default_line_item_discount' => '1',
            'subtotal1' => '1',
            'subtotal2' => '1',
            'subtotal3' => '1',
            'default_line_item_tax' => '1',
            'default_line_item_description' => '1',
            'default_subtotal_discount'=> '1',
            'default_subtotal_tax' => '1',
            'default_subtotal_shipping_and_handling' => '1',
            'invoice_prefix' => 'WM',
            'invoice_number_digit' => '5',
            'invoice_start_number' => '1',
            'item_quantity_decimal_place' => '2',
            'item_tax_decimal_place' => '2',
            'item_subtotal1_decimal_place' => '2',
            'item_subtotal2_decimal_place' => '2',
            'item_subtotal3_decimal_place' => '2',
            'item_discount_decimal_place' => '2',
            'shipping_and_handling_decimal_place' => '2',
            'quotation_prefix' => 'WM',
            'quotation_number_digit' => '5',
            'quotation_start_number' => '1',
            'random_transaction_reference_number' => '1',
            'allowed_upload_file' => 'jpg,png,doc,docx,pdf,txt',
            'max_file_size_upload' => 1
        ],
        'default_role' => 'admin',
        'default_customer_role' => 'customer',
        'default_staff_role' => 'staff',
        'default_department' => 'System Administration',
        'default_designation' => 'System Administrator',
        'item_code' => 'PAY2017',
        'storage_root' => '/app/uploads/',
        'upload_path' => [
            'company_logo' => 'uploads/logo/',
            'avatar' => 'uploads/avatar/',
            'app_logo' => 'uploads/applogo/',
        ],
        'ignore_var' => array('_token','config_type','ajax_submit'),
        'path' => [
            'country' => '/config/country.php',
            'timezone' => '/config/timezone.php',
            'translation' => '/config/translation.php',
            'localization' => '/config/localization.php',
            'verifier' => 'http://envato.wmlab.in/',
            'config' => '/config/config.php',
            'mail' => '/config/mail.php',
            'service' => '/config/services.php',
        ],
        'social_login_provider' => [
            'facebook','twitter','google','github'
        ],
        'payment_gateways' => [
            'paypal','stripe','tco','payumoney'
        ],
        'max_file_allowed' => [
            'message' => 5,
            'announcement' => 5,
            'invoice' => 5,
            'quotation' => 5,
            'income' => 5,
            'expense' => 5,
            'account-transfer' => 5,
            'invoice-payment' => 5,
        ]
	);
?>