<?php
return array(
	'staff' => 'NAME, USERNAME, EMAIL, COMPANY_NAME, COMPANY_EMAIL, COMPANY_PHONE, COMPANY_WEBSITE, CURRENT_DATE_TIME, CURRENT_DATE, DATE_OF_BIRTH, DATE_OF_ANNIVERSARY, DEPARTMENT, DESIGNATION', 
	'customer' => 'NAME, USERNAME, EMAIL, COMPANY_NAME, COMPANY_EMAIL, COMPANY_PHONE, COMPANY_WEBSITE, CURRENT_DATE_TIME, CURRENT_DATE, DATE_OF_BIRTH, DATE_OF_ANNIVERSARY', 
	'invoice' => 'CUSTOMER_NAME, CUSTOMER_EMAIL, CUSTOMER_PHONE, INVOICE_NUMBER, REFERENCE_NUMBER, INVOICE_DATE, DUE_DATE, INVOICE_TOTAL, INVOICE_LINK',
	);